//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Context
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

    
    public partial class Admin_Login
    {
		[Required(ErrorMessage = "Admin_Id is required")]
		public int Admin_ID { get; set; }

		[Required(ErrorMessage = "Admin_Name is required")]
		public string Admin_Name { get; set; }

		[Required(ErrorMessage ="Password is required")]
		[DataType(DataType.Password)]
        public string Admin_Password { get; set; }
    }
}
