//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Context
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
    
    public partial class AdminTable
    {
		//validating Admmin_ID
		[Required(ErrorMessage = "*The Admin_ID is Required")]
		[Range(1000,2000 , ErrorMessage = "Enter number between 1000 to 2000")]
		public int Admin_ID { get; set; }

		//Validating Admin_Name
        [Required(ErrorMessage = "*The Admin_Name is Required")]
		[MaxLength(20)]
		public string Admin_Name { get; set; }

		//Validating Admin_Password
		[Required(ErrorMessage = "*This field is Required")]
		[DataType(DataType.Password)]		
		public string Admin_Password { get; set; }
		[Compare("Admin_Password")]
		[DisplayName("Confirm Password")]
		public string Confirm_Password { get; set; }

		//Validating Date of Birth
		[Required(ErrorMessage ="*Date of Birth is required")]
		[DataType(DataType.Date)]
		public string DateOfBirth { get; set; }

		//Validating Contact Number
		[Required(ErrorMessage = "*Contact is Required")]
		[DataType(DataType.PhoneNumber)]
		[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "*Not a valid Phone number")]
		public string Admin_Contact { get; set; }
    }
}
