//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Context
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Shows = new HashSet<Show>();
            this.Theatres = new HashSet<Theatre>();
        }
    
		[Required(ErrorMessage ="*Movie_ID is required")]
        public int Movie_ID { get; set; }

		[Required(ErrorMessage = "*Movie_Name is required")]
		public string Movie_Name { get; set; }

		[Required(ErrorMessage = "*Movie_Genre is required")]
		public string Genre { get; set; }

		
		[Required(ErrorMessage = "*Movie_Director is required")]	
		public string Director { get; set; }


		[DataType(DataType.Time)]
		[Required(ErrorMessage ="*Length of the movie is required")]
		public Nullable<System.TimeSpan> Movie_Length { get; set; }

		[Required(ErrorMessage = "*Language is required")]
		public string Languages { get; set; }

		[Required(ErrorMessage ="*Release date is required")]
		[DataType(DataType.Date)]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Show> Shows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Theatre> Theatres { get; set; }
    }
}
