//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Context
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
    
    public partial class Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Screen()
        {
            this.Shows = new HashSet<Show>();
        }

		//Validating Screen Id and it is required
		[Required(ErrorMessage ="*Screen_ID is required")]
        public int Screen_ID { get; set; }


		//Validating Theatre Id and it is required
		[Required(ErrorMessage = "*TheatreID is required")]
		public Nullable<int> TheatreID { get; set; }

		//Validating Screen Name and it is required
		[Required(ErrorMessage = "*Screen Name is required")]
		public string ScreenName { get; set; }

		//Validating No Of Rows and it is required
		[Required(ErrorMessage = "*No Of Rows is required")]
		public Nullable<int> No_Of_Rows { get; set; }

		//Validating No Of Columnss and it is required
		[Required(ErrorMessage = "*No of Columns is required")]
		public Nullable<int> No_Of_Columns { get; set; }
    
        public virtual Theatre Theatre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Show> Shows { get; set; }
    }
}
