//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Context
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class Show
    {
		//Validating Show ID is required
		[Required(ErrorMessage ="*ID is required")]
        public int Show_ID { get; set; }

		//Validating StartTime 
		[Required(ErrorMessage ="*Mention Start Time")]
		[DataType(DataType.Time)]
        public Nullable<System.TimeSpan> ShowStartTime { get; set; }

		//Mentioning the End Time  
		[Required(ErrorMessage = "*Mention End Time")]
		[DataType(DataType.Time)]
		public Nullable<System.TimeSpan> ShowEndTime { get; set; }

		//Validating Seat_Id is required
		//[Required(ErrorMessage ="Seat_ID is required")]
        public Nullable<int> Seat_ID { get; set; }

		//
		[Required(ErrorMessage ="*Name of the show is required")]
        public string ShowName { get; set; }

		//Validating the Theatre ID is required
		[Required(ErrorMessage ="*TheatreID is required")]
        public Nullable<int> TheatreID { get; set; }


		//Validating Movie Name is required
		[Required(ErrorMessage ="*MovieName is required")]
        public Nullable<int> MovieName { get; set; }

		//Validating Screen Id and it is required
		[Required(ErrorMessage ="*ScreenId is required")]
        public Nullable<int> ScreenID { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Screen Screen { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Theatre Theatre { get; set; }
    }
}
