//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Context
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
    
    public partial class Theatre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Theatre()
        {
            this.Screens = new HashSet<Screen>();
            this.Shows = new HashSet<Show>();
        }
    
		//Validating Theatre ID
		[Required(ErrorMessage = "*Theatre ID is required")]
        public int Theatre_ID { get; set; }

		//Validating Theatre Name
		[Required(ErrorMessage = "*Theatre Name is required")]
		public string Theatre_Name { get; set; }

		//City is required
		[Required(ErrorMessage = "*City is required")]
		public string Theatre_City { get; set; }

		//Movie ID is required
		[DisplayName("Movie")]
        public Nullable<int> MovieID { get; set; }

		//Manager Name is required
		[Required(ErrorMessage ="*Manager Name is required")]
        public string Manager_Name { get; set; }

		//Manager Contact is required
		[Required(ErrorMessage ="*Manager Contact is reequired")]
		[DataType(DataType.PhoneNumber)]
		[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "*Not a valid Phone number")]
		public Nullable<long> Manager_Contact { get; set; }
    
        public virtual Movie Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Screen> Screens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Show> Shows { get; set; }
    }
}
